/**:
  ros__parameters:
    robot_base_frame: base_link
    return_to_init: false
    costmap_topic: /global_costmap/costmap
    costmap_updates_topic: map_updates
    visualize: true
    planner_frequency: 0.15
    progress_timeout: 60.0
    potential_scale: 0.1
    orientation_scale: 0.0
    gain_scale: 0.0
    transform_tolerance: 1.0
    min_frontier_size: 0.5